apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: prometheus-cluster
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'contacts-api'
        metrics_path: /metrics
        static_configs:        
          - targets: ['contacts-api.contacts-api-cluster.svc.cluster.local:80']
        
      - job_name: 'contact-delete-consumer'
        metrics_path: /metrics
        static_configs:
          - targets: [ 'contact-delete-consumer-worker.contacts-delete-cluster.svc.cluster.local:80' ]
        
      - job_name: 'contact-insert-consumer'
        metrics_path: /metrics
        static_configs:
          - targets: [ 'contact-insert-consumer-worker.contacts-insert-cluster.svc.cluster.local:80' ]
        
      - job_name: 'contact-update-consumer'
        metrics_path: /metrics
        static_configs:
          - targets: [ 'contact-update-consumer-worker.contacts-update-cluster.svc.cluster.local:80' ]