apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: prometheus-cluster
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus-server