apiVersion: v1
kind: Service
metadata:
  name: contact-insert-consumer-worker
  namespace: contacts-insert-cluster
spec:
  selector:
    app: contact-insert-consumer-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP