apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq-cluster
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  selector:
    app: rabbitmq
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: rabbitmq-cluster
spec:
  ports:
    - port: 15672
      targetPort: 15672
      name: management
    - port: 5672
      targetPort: 5672
      name: amqp
  selector:
    app: rabbitmq
  type: NodePort
