apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-configmap
  namespace: contacts-api-cluster
  labels:
    app: contacts-configmap
data: 
  MASS_TRANSIT_DELETE_QUEUE_NAME: contact-delete-queue
  MASS_TRANSIT_INSERT_QUEUE_NAME: contact-insert-queue
  MASS_TRANSIT_UPDATE_QUEUE_NAME: contact-update-queue
  MASS_TRANSIT_HOST: rabbitmq.rabbitmq-cluster.svc.cluster.local
  MASS_TRANSIT_PORT: "5672"