apiVersion: v1
kind: Service
metadata:
  name: contacts-api
  namespace: contacts-api-cluster
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
  selector:
    app: contacts-api