apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api
  labels:
    app: contacts-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts-api
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
      - name: contacts-api
        image: lucasfm95/fiap-tech-challenge-fase3:latest
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
          requests:
            memory: "128Mi"
            cpu: "0.25"
        env:
        - name: CONNECTION_STRING_DB_POSTGRES
          secretKeyRef:
            name: contacts-secret
            key: CONNECTION_STRING_DB_POSTGRES
        - name: MASS_TRANSIT_USERNAME
          secretKeyRef:
            name: contacts-secret
            key: MASS_TRANSIT_USERNAME
        - name: MASS_TRANSIT_PASSWORD
          secretKeyRef:
            name: contacts-secret
            key: MASS_TRANSIT_PASSWORD
        - name: MASS_TRANSIT_DELETE_QUEUE_NAME
          configMapKeyRef:
            name: contacts-configmap
            key: MASS_TRANSIT_DELETE_QUEUE_NAME
        - name: MASS_TRANSIT_INSERT_QUEUE_NAME
          configMapKeyRef:
            name: contacts-configmap
            key: MASS_TRANSIT_INSERT_QUEUE_NAME
        - name: MASS_TRANSIT_UPDATE_QUEUE_NAME
          configMapKeyRef:
            name: contacts-configmap
            key: MASS_TRANSIT_UPDATE_QUEUE_NAME
        - name: MASS_TRANSIT_HOST
          configMapKeyRef:
            name: contacts-configmap
            key: MASS_TRANSIT_HOST
        - name: MASS_TRANSIT_PORT
          configMapKeyRef:
            name: contacts-configmap
            key: MASS_TRANSIT_PORT