apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
      protocol: TCP
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
      requests:
        memory: "256Mi"
        cpu: "0.5"
    env:
    - name: POSTGRES_USER
      secretKeyRef:
        name: contacts-secret
        key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      secretKeyRef:
        name: contacts-api-secret
        key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      secretKeyRef:
        name: contacts-api-secret
        key: POSTGRES_DB