apiVersion: v1
kind: Service
metadata:
  name: contacts-api
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32000
  selector:
    app: contacts-api