apiVersion: v1
kind: Service
metadata:
  name: contact-delete-consumer-worker
spec:
  selector:
    app: contact-delete-consumer-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP