{
 "title": "prometheus-net",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "The duration of HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Start time of the process",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance =~ \"$instances\"} * 1000"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process working set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Tech Challenge Contacts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request count by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fiap_tech_challenge_api_request_counter{endpoint!=\"/metrics\"}",
     "legendFormat": "{{endpoint}}-{{method}}"
    }
   ]
  },
  {
   "title": "Request por status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Duração HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Contacts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "QTD Requests Insert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_insert_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD Processed Insert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inserted_contact_total_processed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QTD Requests Update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_update_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD Processed Update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "updated_contact_total_processed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QTD Requests Delete",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_delete_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD Processed Delete",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deleted_contact_total_processed",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}