apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: postgres-cluster
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_DB: ZmlhcF90ZWNoX2NoYWxsZW5nZQ==
  CONNECTION_STRING_DB_POSTGRES: "SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9YWRtaW47RGF0YWJhc2U9ZmlhcF90ZWNoX2NoYWxsZW5nZQ=="