apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgres-cluster
  labels:
    type: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data