apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: postgres-cluster
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
      protocol: TCP
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
      requests:
        memory: "256Mi"
        cpu: "0.5"
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgre-secret
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgre-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: postgre-secret
          key: POSTGRES_DB
    volumeMounts:
    - name: postgres-storage
      mountPath: /var/lib/postgresql/data
    - name: postgres-initdb
      mountPath: /docker-entrypoint-initdb.d/
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pvc
  - name: postgres-initdb
    configMap:
      name: configmap-init-db